### ISSUE TITLE
Did you have documentation to create this?

### ISSUE THREAD

**Issue by kylebrowning** [jaimehgb/RaiBlocksPHP#1]
Im trying to convert some of this to swift, but curious where you got the docs to create this?

**Comment by jaimehgb** [comment]
There weren't any docs by that time :P 

You have it all here:
https://github.com/clemahieu/raiblocks

Maybe here too:
https://raiblocks.net/media/RaiBlocks_Whitepaper__English.pdf

**Comment by kylebrowning** [comment]
thanks for the quick response. How did you go about testing these transactions? Did you  just get opening accounts working, and then send XRB between them?
